fixup tty code in general to use autotools
git-svn-id: svn://localhost/svn/toolchain/trunk@1876 2adf4935-75e9-4407-93b2-34b21a1880a4

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -694,6 +694,7 @@ AUTOM4TE
 CPP
 GREP
 EGREP
+PTY_LIB
 LIBOBJS
 LTLIBOBJS'
 ac_subst_files=''
@@ -1653,6 +1654,7 @@ ac_header_list="$ac_header_list fcntl.h"
 ac_header_list="$ac_header_list getopt.h"
 ac_header_list="$ac_header_list libgen.h"
 ac_header_list="$ac_header_list pthread.h"
+ac_header_list="$ac_header_list pty.h"
 ac_header_list="$ac_header_list signal.h"
 ac_header_list="$ac_header_list stdbool.h"
 ac_header_list="$ac_header_list stdint.h"
@@ -1662,6 +1664,7 @@ ac_header_list="$ac_header_list strings.h"
 ac_header_list="$ac_header_list termios.h"
 ac_header_list="$ac_header_list time.h"
 ac_header_list="$ac_header_list unistd.h"
+ac_header_list="$ac_header_list util.h"
 ac_header_list="$ac_header_list sys/endian.h"
 ac_header_list="$ac_header_list sys/mman.h"
 ac_header_list="$ac_header_list sys/stat.h"
@@ -4442,22 +4445,94 @@ done
 
 
 
-for ac_header in elf.h
-do
-as_ac_Header=`echo "ac_cv_header_$ac_header" | $as_tr_sh`
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
-  { echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+
+
+
+
+
+
+
+{ echo "$as_me:$LINENO: checking for openpty in -lutil" >&5
+echo $ECHO_N "checking for openpty in -lutil... $ECHO_C" >&6; }
+if test "${ac_cv_lib_util_openpty+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lutil  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char openpty ();
+int
+main ()
+{
+return openpty ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_util_openpty=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_util_openpty=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_util_openpty" >&5
+echo "${ECHO_T}$ac_cv_lib_util_openpty" >&6; }
+if test $ac_cv_lib_util_openpty = yes; then
+  PTY_LIB="-lutil"
+else
+  PTY_LIB=""
+fi
+
+
+
+if test "${ac_cv_header_elf_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for elf.h" >&5
+echo $ECHO_N "checking for elf.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_elf_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 fi
-ac_res=`eval echo '${'$as_ac_Header'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_elf_h" >&5
+echo "${ECHO_T}$ac_cv_header_elf_h" >&6; }
 else
   # Is the header compilable?
-{ echo "$as_me:$LINENO: checking $ac_header usability" >&5
-echo $ECHO_N "checking $ac_header usability... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking elf.h usability" >&5
+echo $ECHO_N "checking elf.h usability... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -4465,7 +4540,7 @@ cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 $ac_includes_default
-#include <$ac_header>
+#include <elf.h>
 _ACEOF
 rm -f conftest.$ac_objext
 if { (ac_try="$ac_compile"
@@ -4497,15 +4572,15 @@ rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
 echo "${ECHO_T}$ac_header_compiler" >&6; }
 
 # Is the header present?
-{ echo "$as_me:$LINENO: checking $ac_header presence" >&5
-echo $ECHO_N "checking $ac_header presence... $ECHO_C" >&6; }
+{ echo "$as_me:$LINENO: checking elf.h presence" >&5
+echo $ECHO_N "checking elf.h presence... $ECHO_C" >&6; }
 cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
-#include <$ac_header>
+#include <elf.h>
 _ACEOF
 if { (ac_try="$ac_cpp conftest.$ac_ext"
 case "(($ac_try" in
@@ -4538,25 +4613,25 @@ echo "${ECHO_T}$ac_header_preproc" >&6; }
 # So?  What about this header?
 case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
   yes:no: )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&5
-echo "$as_me: WARNING: $ac_header: accepted by the compiler, rejected by the preprocessor!" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the compiler's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the compiler's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: elf.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: elf.h: proceeding with the compiler's result" >&2;}
     ac_header_preproc=yes
     ;;
   no:yes:* )
-    { echo "$as_me:$LINENO: WARNING: $ac_header: present but cannot be compiled" >&5
-echo "$as_me: WARNING: $ac_header: present but cannot be compiled" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     check for missing prerequisite headers?" >&5
-echo "$as_me: WARNING: $ac_header:     check for missing prerequisite headers?" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: see the Autoconf documentation" >&5
-echo "$as_me: WARNING: $ac_header: see the Autoconf documentation" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&5
-echo "$as_me: WARNING: $ac_header:     section \"Present But Cannot Be Compiled\"" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: proceeding with the preprocessor's result" >&5
-echo "$as_me: WARNING: $ac_header: proceeding with the preprocessor's result" >&2;}
-    { echo "$as_me:$LINENO: WARNING: $ac_header: in the future, the compiler will take precedence" >&5
-echo "$as_me: WARNING: $ac_header: in the future, the compiler will take precedence" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: elf.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: elf.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: elf.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: elf.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: elf.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: elf.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: elf.h: in the future, the compiler will take precedence" >&2;}
     ( cat <<\_ASBOX
 ## ------------------------------------------ ##
 ## Report this to vapier@blackfin.uclinux.org ##
@@ -4565,45 +4640,58 @@ _ASBOX
      ) | sed "s/^/$as_me: WARNING:     /" >&2
     ;;
 esac
-{ echo "$as_me:$LINENO: checking for $ac_header" >&5
-echo $ECHO_N "checking for $ac_header... $ECHO_C" >&6; }
-if { as_var=$as_ac_Header; eval "test \"\${$as_var+set}\" = set"; }; then
+{ echo "$as_me:$LINENO: checking for elf.h" >&5
+echo $ECHO_N "checking for elf.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_elf_h+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  eval "$as_ac_Header=\$ac_header_preproc"
+  ac_cv_header_elf_h=$ac_header_preproc
 fi
-ac_res=`eval echo '${'$as_ac_Header'}'`
-	       { echo "$as_me:$LINENO: result: $ac_res" >&5
-echo "${ECHO_T}$ac_res" >&6; }
+{ echo "$as_me:$LINENO: result: $ac_cv_header_elf_h" >&5
+echo "${ECHO_T}$ac_cv_header_elf_h" >&6; }
 
 fi
-if test `eval echo '${'$as_ac_Header'}'` = yes; then
-  cat >>confdefs.h <<_ACEOF
-#define `echo "HAVE_$ac_header" | $as_tr_cpp` 1
+if test $ac_cv_header_elf_h = yes; then
+
+
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_ELF_H 1
 _ACEOF
+
 
 else
 
-	if test -f "$ac_top_srcdir/../uClibc/include/elf.h" ; then
+	if test -f "$srcdir/../uClibc/include/elf.h" ; then
 				sed \
 			-e "/features.h/d" \
 			-e "/__BEGIN_DECLS/d" \
 			-e "/__END_DECLS/d" \
-			"$ac_top_srcdir/../uClibc/include/elf.h" > "$ac_top_builddir/elf.h"
+			"$srcdir/../uClibc/include/elf.h" > elf.h
 	else
 		{ { echo "$as_me:$LINENO: error: unable to locate a usable elf.h" >&5
 echo "$as_me: error: unable to locate a usable elf.h" >&2;}
    { (exit 1); exit 1; }; }
 	fi
 
+cat >>confdefs.h <<\_ACEOF
+#define HAVE_LOCAL_ELF_H 1
+_ACEOF
+
+
 fi
 
-done
 
 
 ac_config_commands="$ac_config_commands tests/atconfig"
 
 
+
+if test "$GCC" = yes; then
+	CFLAGS="$CFLAGS -Wall"
+fi
+#if test "$USER" = vapier; then
+#	CFLAGS="$CFLAGS -Werror"
+#fi
 
 ac_config_files="$ac_config_files Makefile tests/atlocal tests/Makefile tests/package.m4"
 
@@ -5332,11 +5420,12 @@ AUTOM4TE!$AUTOM4TE$ac_delim
 CPP!$CPP$ac_delim
 GREP!$GREP$ac_delim
 EGREP!$EGREP$ac_delim
+PTY_LIB!$PTY_LIB$ac_delim
 LIBOBJS!$LIBOBJS$ac_delim
 LTLIBOBJS!$LTLIBOBJS$ac_delim
 _ACEOF
 
-  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 81; then
+  if test `sed -n "s/.*$ac_delim\$/X/p" conf$$subs.sed | grep -c X` = 82; then
     break
   elif $ac_last_try; then
     { { echo "$as_me:$LINENO: error: could not make $CONFIG_STATUS" >&5
